version: "3"
services:
  queueapi:
    build:
      context: queue_api
    image: queueapi
    environment:
      - VIRTUAL_HOST=api.ichdev.net
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=api.ichdev.net
    networks:
      - webproxy
  start_call:
    build:
      context: initiate_call
    image: startcall
    environment:
      - VIRTUAL_HOST=call.ichdev.net
      - LETSENCRYPT_HOST=call.ichdev.net
    networks:
      - webproxy

networks:
  webproxy:
    external:
      name: webproxy