version: "3"
services:
  start_call:
    build:
      context: initiate_call
    image: startcall
    ports:
      - "8080:80"
    environment:
      - VIRTUAL_HOST=call.ichdev.net
      - LETSENCRYPT_HOST=call.ichdev.net
    networks:
      - webproxy

networks:
  webproxy:
    external:
      name: webproxy